name: Elixir CI

on: push

jobs:
  checks:
    runs-on: ubuntu-latest

    services:
      dgraph:
        image: dgraph/standalone
        ports:
          - 8000:8000
          - 8080:8080
          - 9080:9080
        options: --health-cmd "curl -sSf http://localhost:8080/health"

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1
      with:
        otp-version: 22.2.2
        elixir-version: 1.9.4

    # Caching
    - name: Dependencies cache
      uses: actions/cache@v1
      with:
        path: deps
        key: deps-${{ hashFiles('mix.lock') }}
    - name: Build cache
      uses: actions/cache@v1
      with:
        path: _build
        key: build-${{ hashFiles('mix.lock') }}

    # Setup
    - name: Install dependencies
      run: mix deps.get

    # Checks
    - name: Compiler warnings
      run: mix compile --warnings-as-errors --force
    - name: Code format
      run: mix format --check-formatted --dry-run
    - name: Code conventions (Credo)
      run: mix credo
    - name: Test suite
      run: mix test
      env:
        WARNINGS_AS_ERRORS: true
        DGRAPH_HOST: dgraph
        DGRAPH_PORT: ${{ job.services.dgraph.ports[9080] }}
    - name: Static code analysis (Dialyzer)
      run: mix dialyzer
